### PR TITLE
update rust version to support simd

### PR DESCRIPTION
**Pull request by GuyPozner**
Checklist
* [V] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [V] Bumped the build number (if the version is unchanged)
* [V] Reset the build number to `0` (if the version changed)
* [V] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

@xhochy , can you please take a look? I would love some help understanding why it cannot use the 1.79 rust version which we have just released. Thanks :)

### CODE REVIEW

**Comment by xhochy** [comment]
We need https://github.com/conda-forge/rust-activation-feedstock/pull/61

**Comment by xhochy** [comment]
@0xbe7a @pavelzw another Segfault. Do we have a central tracking issue for this?

**Comment by 0xbe7a** [comment]
I have tracked all known failures in https://github.com/conda-forge/polars-feedstock/issues/259 so far

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

We have updated rust meanwhile a bit, let's see whether that changed something here.

**Comment by thewchan** [comment]
Looks like it's working! Thanks all

**Pull request merged**
